//! Product E3: C-produced fixtures only (PR-B09 / COL-007 done evidence).
//!
//! Fixtures under `fixtures/v6/from-c/**` are generated by
//! `make -C collector gen-e3-fixtures` (`collector/t/gen_e3_c_fixtures.c`).
//! Tests MUST load those bytes — never re-encode via `e3_standin_*`.
//!
//! Evidence: `cargo test -p nytprof-format-v6 e3_c_` ·
//! `./tools/oracle/e3_c_writer_parity.sh`

use std::path::PathBuf;

use nytprof_format_v6::chunk::codec;
use nytprof_format_v6::compressed_profile::OwnedEventRecord;
use nytprof_format_v6::decoded_event::{
    decode_decoded_event_profile, decode_decoded_event_profile_with_string_dict,
};
use nytprof_format_v6::{e3_assert_logical_equal, e3_decode_writer_bytes};

fn from_c_fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/v6/from-c")
        .join(name)
}

fn load_c_bytes(name: &str) -> Vec<u8> {
    let path = from_c_fixture(name);
    std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "product E3 requires C fixture {path:?}: {e} \
             (regenerate: make -C collector gen-e3-fixtures OUTDIR=fixtures/v6/from-c)"
        )
    })
}

/// Product E3 absolute EVENT: C absolute sink → always-inflate logical sites.
#[test]
fn e3_c_absolute_event_logical_equal() {
    let wire = load_c_bytes("absolute.nytprof");
    let e3 = e3_decode_writer_bytes(&wire, true, false).expect("E3-C absolute decode");
    assert_eq!(e3.bytes_consumed, wire.len());
    assert!(e3.dict.is_none());
    assert_eq!(e3.profile.records.len(), 4);
    assert_eq!(e3.profile.event_chunk_count, 1);
    match &e3.profile.records[0] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (1, 10, 5));
        }
        other => panic!("[0] {other:?}"),
    }
    match &e3.profile.records[1] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (1, 11, 6));
        }
        other => panic!("[1] {other:?}"),
    }
    match &e3.profile.records[2] {
        OwnedEventRecord::TimeBlock {
            fid,
            line,
            block_line,
            ticks,
        } => {
            assert_eq!((*fid, *line, *block_line, *ticks), (1, 12, 4, 20));
        }
        other => panic!("[2] {other:?}"),
    }
    match &e3.profile.records[3] {
        OwnedEventRecord::SubEntry {
            caller_fid,
            caller_line,
        } => {
            assert_eq!((*caller_fid, *caller_line), (1, 10));
        }
        other => panic!("[3] {other:?}"),
    }
    // Independent re-decode of the same C bytes (no stand-in write).
    let (expected, n2) = decode_decoded_event_profile(&wire, true).unwrap();
    assert_eq!(n2, wire.len());
    e3_assert_logical_equal(&e3.profile, &expected.records, &expected.sequences)
        .expect("E3-C absolute equality");
}

/// Product E3 packing multi-chunk: C packing sink → continuous sites + seq.
#[test]
fn e3_c_packing_multi_chunk_logical_equal() {
    let wire = load_c_bytes("packing.nytprof");
    let e3 = e3_decode_writer_bytes(&wire, true, false).expect("E3-C packing decode");
    assert_eq!(e3.bytes_consumed, wire.len());
    assert!(e3.profile.event_chunk_count >= 2);
    assert_eq!(e3.profile.records.len(), 4);
    match &e3.profile.records[0] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (1, 10, 5));
        }
        other => panic!("[0] {other:?}"),
    }
    match &e3.profile.records[1] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (1, 11, 6));
        }
        other => panic!("[1] {other:?}"),
    }
    // Packing path carries FLAG_HAS_SEQ → continuous seq 0..n-1.
    assert_eq!(e3.profile.sequences.len(), e3.profile.records.len());
    for (i, s) in e3.profile.sequences.iter().enumerate() {
        assert_eq!(*s, Some(i as u64), "seq[{i}]");
    }
    let (expected, _) = decode_decoded_event_profile(&wire, true).unwrap();
    e3_assert_logical_equal(&e3.profile, &expected.records, &expected.sequences)
        .expect("E3-C packing equality");
}

/// Product E3 FOOTER string-dict: C dict sink → resolved ATTRIBUTE/COMMENT.
#[test]
fn e3_c_dict_footer_resolve() {
    let wire = load_c_bytes("dict.nytprof");
    let e3 = e3_decode_writer_bytes(&wire, true, true).expect("E3-C dict decode");
    assert_eq!(e3.bytes_consumed, wire.len());
    assert!(e3.profile.has_footer);
    let dict = e3.dict.as_ref().expect("dict present");
    assert!(dict.len() >= 2);
    assert_eq!(e3.profile.records.len(), 3);
    match &e3.profile.records[0] {
        OwnedEventRecord::Attribute { key, value } => {
            assert_eq!(key, b"basetime");
            assert_eq!(value, b"1786111723");
        }
        other => panic!("[0] {other:?}"),
    }
    match &e3.profile.records[1] {
        OwnedEventRecord::Comment { text } => {
            assert_eq!(text, b"e3-c-dict-label");
        }
        other => panic!("[1] {other:?}"),
    }
    match &e3.profile.records[2] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (1, 10, 5));
        }
        other => panic!("[2] {other:?}"),
    }
    let (expected, expected_dict, _) =
        decode_decoded_event_profile_with_string_dict(&wire, true).unwrap();
    assert_eq!(dict.len(), expected_dict.len());
    e3_assert_logical_equal(&e3.profile, &expected.records, &expected.sequences)
        .expect("E3-C dict equality");
}

/// Product E3 packing + FOOTER dict multi-chunk.
#[test]
fn e3_c_packing_dict_multi_chunk() {
    let wire = load_c_bytes("packing_dict.nytprof");
    let e3 = e3_decode_writer_bytes(&wire, true, true).expect("E3-C packing+dict");
    assert_eq!(e3.bytes_consumed, wire.len());
    assert!(e3.profile.event_chunk_count >= 2);
    assert!(e3.profile.has_footer);
    assert_eq!(e3.profile.records.len(), 4);
    match &e3.profile.records[0] {
        OwnedEventRecord::Comment { text } => assert_eq!(text, b"pack-dict-mark"),
        other => panic!("[0] {other:?}"),
    }
    match &e3.profile.records[1] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (1, 10, 5));
        }
        other => panic!("[1] {other:?}"),
    }
    match &e3.profile.records[2] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (1, 11, 6));
        }
        other => panic!("[2] {other:?}"),
    }
    match &e3.profile.records[3] {
        OwnedEventRecord::Comment { text } => assert_eq!(text, b"# pack-dict-end"),
        other => panic!("[3] {other:?}"),
    }
    assert_eq!(e3.profile.sequences.len(), e3.profile.records.len());
    for (i, s) in e3.profile.sequences.iter().enumerate() {
        assert_eq!(*s, Some(i as u64), "seq[{i}]");
    }
    let (expected, _, _) = decode_decoded_event_profile_with_string_dict(&wire, true).unwrap();
    e3_assert_logical_equal(&e3.profile, &expected.records, &expected.sequences)
        .expect("E3-C packing+dict equality");
}

/// Product E3 mid-stream packing continuity (NONE→ZLIB + TIME_LINE_RUN site-delta).
#[test]
fn e3_c_mid_stream_packing_continuity() {
    let wire = load_c_bytes("mid_stream.nytprof");
    let e3 = e3_decode_writer_bytes(&wire, true, false).expect("E3-C mid-stream");
    assert_eq!(e3.bytes_consumed, wire.len());
    assert_eq!(e3.profile.event_chunk_count, 2);
    assert_eq!(
        e3.profile.event_chunk_codecs,
        vec![codec::NONE, codec::ZLIB]
    );
    // TL + 2 expanded run + StartDeflate + post TL + SubEntry + TimeBlock = 7
    assert_eq!(e3.profile.records.len(), 7);
    match &e3.profile.records[0] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (1, 10, 5));
        }
        other => panic!("[0] {other:?}"),
    }
    // Expanded TIME_LINE_RUN at (2,50) ticks 7,8
    match &e3.profile.records[1] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (2, 50, 7));
        }
        other => panic!("[1] {other:?}"),
    }
    match &e3.profile.records[2] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (2, 50, 8));
        }
        other => panic!("[2] {other:?}"),
    }
    assert!(matches!(
        e3.profile.records[3],
        OwnedEventRecord::StartDeflate
    ));
    // Post-run site-delta lands on (2,51,9)
    match &e3.profile.records[4] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (2, 51, 9));
        }
        other => panic!("[4] post site-delta {other:?}"),
    }
    match &e3.profile.records[5] {
        OwnedEventRecord::SubEntry {
            caller_fid,
            caller_line,
        } => {
            assert_eq!((*caller_fid, *caller_line), (2, 50));
        }
        other => panic!("[5] {other:?}"),
    }
    match &e3.profile.records[6] {
        OwnedEventRecord::TimeBlock {
            fid,
            line,
            block_line,
            ticks,
        } => {
            assert_eq!((*fid, *line, *block_line, *ticks), (3, 9, 7, 3));
        }
        other => panic!("[6] {other:?}"),
    }
    // Seq continuous across switch (StartDeflate also assigned under packing).
    assert_eq!(e3.profile.sequences.len(), e3.profile.records.len());
    for (i, s) in e3.profile.sequences.iter().enumerate() {
        assert_eq!(*s, Some(i as u64), "seq[{i}]");
    }
    let (expected, _) = decode_decoded_event_profile(&wire, true).unwrap();
    e3_assert_logical_equal(&e3.profile, &expected.records, &expected.sequences)
        .expect("E3-C mid-stream equality");
}

/// Product E3 mid-stream packing + FOOTER dict (NONE→ZSTD).
#[test]
fn e3_c_mid_stream_dict_packing() {
    let wire = load_c_bytes("mid_stream_dict.nytprof");
    let e3 = e3_decode_writer_bytes(&wire, true, true).expect("E3-C mid-stream dict");
    assert_eq!(e3.bytes_consumed, wire.len());
    assert_eq!(e3.profile.event_chunk_count, 2);
    assert_eq!(
        e3.profile.event_chunk_codecs,
        vec![codec::NONE, codec::ZSTD]
    );
    assert!(e3.profile.has_footer);
    let dict = e3.dict.as_ref().unwrap();
    assert!(dict.len() >= 2);
    // TL + 2 run + StartDeflate + post TL + SubEntry + 2 comments = 8
    assert_eq!(e3.profile.records.len(), 8);
    match &e3.profile.records[4] {
        OwnedEventRecord::TimeLine { fid, line, ticks } => {
            assert_eq!((*fid, *line, *ticks), (2, 51, 9));
        }
        other => panic!("[4] {other:?}"),
    }
    let n = e3.profile.records.len();
    match &e3.profile.records[n - 2] {
        OwnedEventRecord::Comment { text } => {
            assert_eq!(text, b"ms-e3-c-dict-mark");
        }
        other => panic!("mark-comment {other:?}"),
    }
    match &e3.profile.records[n - 1] {
        OwnedEventRecord::Comment { text } => {
            assert_eq!(text, b"# ms-e3-c-dict-end");
        }
        other => panic!("end-comment {other:?}"),
    }
    let (expected, _, _) = decode_decoded_event_profile_with_string_dict(&wire, true).unwrap();
    e3_assert_logical_equal(&e3.profile, &expected.records, &expected.sequences)
        .expect("E3-C mid-stream dict equality");
}

/// Product E3 fail-closed: truncated C absolute fixture.
#[test]
fn e3_c_truncated_fail_closed() {
    let wire = load_c_bytes("absolute.nytprof");
    let truncated = &wire[..wire.len().saturating_sub(8).max(8)];
    match e3_decode_writer_bytes(truncated, true, false) {
        Err(_) => {}
        Ok(_) => panic!("truncated C bytes must fail closed"),
    }
}

/// Product E3: matrix files all present and non-empty (manifest gate).
#[test]
fn e3_c_fixture_matrix_present() {
    for name in [
        "absolute.nytprof",
        "packing.nytprof",
        "dict.nytprof",
        "packing_dict.nytprof",
        "mid_stream.nytprof",
        "mid_stream_dict.nytprof",
    ] {
        let b = load_c_bytes(name);
        assert!(
            b.len() > 32 && &b[..8] == b"NYTPROF6",
            "{name}: expected NYTPROF6 magic, len={}",
            b.len()
        );
    }
}
